<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NAIM" failures="1" tests="4" name="Tutorial Ninja functional Regression Test" time="31.293" errors="0" timestamp="2023-10-01T04:05:19 EDT">
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS002_LoginFunctionality" name="r1dot1_TS002_TC001" time="10.093"/>
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS002_LoginFunctionality" name="r1dot1_TS002_TC003" time="7.071">
    <skipped/>
  </testcase> <!-- r1dot1_TS002_TC003 -->
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS002_LoginFunctionality" name="r1dot1_TS002_TC003" time="6.85">
    <skipped/>
  </testcase> <!-- r1dot1_TS002_TC003 -->
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS002_LoginFunctionality" name="r1dot1_TS002_TC003" time="6.066">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.tutorialNinja.functionalTests.R1dot1_TS002_LoginFunctionality.r1dot1_TS002_TC003(R1dot1_TS002_LoginFunctionality.java:39)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- r1dot1_TS002_TC003 -->
</testsuite> <!-- Tutorial Ninja functional Regression Test -->
