<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NAIM" failures="2" tests="16" name="Tutorial Ninja functional Regression Test" time="58.375" errors="0" timestamp="2023-09-28T06:09:49 EDT">
  <testcase classname="com.tutorialNinja.functionalTests.R1dot3_TS012_CheckoutFunctionality" name="R1dot3_TS012_TC001" time="10.302"/>
  <testcase classname="com.tutorialNinja.functionalTests.Draft" name="draftfail" time="10.345">
    <skipped/>
  </testcase> <!-- draftfail -->
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS003_LogoutFunctionality" name="r1dot1_TS003_TC001" time="14.784"/>
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS002_LoginFunctionality" name="r1dot1_TS002_TC001" time="15.139"/>
  <testcase classname="com.tutorialNinja.functionalTests.R1dot2_TS006_ProductCompareFunctionality" name="r1dot2_TS006_TC001" time="17.243"/>
  <testcase classname="com.tutorialNinja.functionalTests.Draft" name="draftfail" time="7.185">
    <skipped/>
  </testcase> <!-- draftfail -->
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS001_RegisterFunctionality" name="r1dot1_TS001_TC001" time="12.977"/>
  <testcase classname="com.tutorialNinja.functionalTests.Draft" name="draftfail" time="5.819">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.tutorialNinja.functionalTests.Draft.draftfail(Draft.java:23)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- draftfail -->
  <testcase classname="com.tutorialNinja.functionalTests.R1dot2_TS005_ProductSearchFunctionality" name="r1dot2_TS005_TC001" time="11.442"/>
  <testcase classname="com.tutorialNinja.functionalTests.Draft" name="loginPagefail" time="5.307">
    <skipped/>
  </testcase> <!-- loginPagefail -->
  <testcase classname="com.tutorialNinja.functionalTests.Draft" name="loginPagefail" time="5.635">
    <skipped/>
  </testcase> <!-- loginPagefail -->
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS001_RegisterFunctionality" name="r1dot1_TS001_TC003" time="16.032"/>
  <testcase classname="com.tutorialNinja.functionalTests.Draft" name="loginPagefail" time="5.015">
    <failure type="java.lang.AssertionError" message="expected [Customer] but found [Account Login]">
      <![CDATA[java.lang.AssertionError: expected [Customer] but found [Account Login]
at com.tutorialNinja.functionalTests.Draft.loginPagefail(Draft.java:32)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- loginPagefail -->
  <testcase classname="com.tutorialNinja.functionalTests.Draft" name="readExcelDraft" time="1.101"/>
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS001_RegisterFunctionality" name="r1dot1_TS001_TC004" time="8.203"/>
  <testcase classname="com.tutorialNinja.functionalTests.R1dot1_TS001_RegisterFunctionality" name="r1dot1_TS001_TC028" time="9.034"/>
</testsuite> <!-- Tutorial Ninja functional Regression Test -->
